INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (1, '', 'BOUNCED CHECK PARK', 'BOUNCED CHECK PARK', 'Yes', 15);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (2, '', 'TICKET SENT FOR CORRECTION/AMENDMENT', 'TICK CORRECTION SENT', 'Yes', 020);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (3, '', 'TICKET CORRECTION/AMENDMENT PROCESSED', 'TKT CORRECTION PROCS', 'Yes', 021);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (4, '', 'CLAIM OF NON OWNERSHIP OF VEHICLE', 'DEC OF NON CLAIM P1', 'Yes', 023);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (5, '', 'LETTER TO NEW OWNER (AS REPORTED BY RO)', 'DEC OF NON NEWLY RPT', 'Yes', 030);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (6, '', 'HEARING HAS BEEN SCHEDULED - INCLUDES INSTRUCTIONS', 'SCHEDULE HEARING LTR', 'Yes', 063);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (7, '', 'UNSENT LETTER TO BUMP SCHEDULED HEARING LETTER TO HISTORY.', 'CANCEL HEARING', 'Yes', 064);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (8, '', 'CANCEL PREVIOUS CORRES SENT THE SAME DAY', 'CANCEL CORRES', 'Yes', 089);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (9, '', 'LIABLE (PARKING)', 'LIABLE (P)', 'Yes', 101);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (10, '', 'NOT LIABLE (PARKING)', 'NOT LIABLE (P)', 'Yes', 102);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (11, '', 'FAILURE TO APPEAR (PARKING)', 'FAILURE TO APPEAR(P)', 'Yes', 103);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (12, '', 'PARKING - REQ FOR INITIAL REVIEW RECD AFTER DEADLINE', 'TOO LATE REVIEW-PKG', 'Yes', 106);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (13, '', 'THE HEARING OFFICER HAS AUTHORIZED A PAYMENT PLAN(PARKING)', 'IPP LIABLE (P)', 'Yes', 107);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (14, '', 'RECEIVED DMV RECEIPT PENDING ACTUAL PAYMENT', 'DMV PROOF OF PAYMENT', 'Yes', 116);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (15, '', 'COMMUNITY SRVC HEARING LIABLE OFFICER COMMENTS (PARKING)', 'CS HRG LIABLE (P)', 'Yes', 119);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (16, '', 'PARKING REFUND', 'PARKING REFUND', 'Yes', 129);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (17, '', 'LIABLE COMMUNITY SERVICE GRANTED (PARKING)', 'LIABLE CMNTY SVC (P)', 'Yes', 130);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (18, '', 'COMMUNITY SERVICE (P) - DEFAULTED-NOT COMPLETED,NO EXTENSION', 'CMNTY SVC REF (P) DF', 'Yes', 133);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (19, '', 'PARKING RETURNED CHECK', 'PKG RETURNED CHECK', 'Yes', 135);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (20, 'D', 'LETTER STATING CITE HAS BEEN DISMISSED', 'CITE DISMISSAL IR', 'Yes', 150);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (21, 'D', 'MONTHLY PARKING PERMIT WAS VALID ON THE DATE OF ISSUANCE', 'VALID PERM DISM', 'No', 151);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (22, '', 'NO FRONT LICENSE PLATES', '5200 PROOF OF CORR', 'Yes', 182);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (23, '', 'PROOF OF CORRECTION-DISMISSED TABS & NO FRONT PLATE-PARKING', 'REC PROOF AND PAY', 'Yes', 183);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (24, '', 'EPIRED REGISTRATION TABS', '5204 PROOF OF CORR', 'Yes', 184);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (25, '', 'PENALTIES - NO FRONT PLATES & TABS', 'PENAL NO FR PLT TAB', 'Yes', 185);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (26, '', 'REC PROOF NOT PAY', 'REC PROOF NOT PAY', 'Yes', 186);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (27, '', '4000(A)(1) INFORMATION', '4000A1 INFORMATION', 'No', 187);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (28, '', 'INSTALLMENT PAYMENT PLAN - ENROLLMENT CONFIRMATION - PARKING', 'IPP ENROL CONF-PARK', 'Yes', 190);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (29, '', 'INSTALLMENT PAYMENT PLAN - NO FIRST PAYMENT - PARKING', 'IPP NO FIRST PAYM PK', 'Yes', 191);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (30, '', 'INSTALLMENT PAYMENT PLAN - NOTICE OF DEFAULT - PARKING', 'IPP-DEFAULT-PARK', 'Yes', 192);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (31, '', 'INSTALLMENT PAYMENT PLAN - ENROLLMENT - PARKING', 'IPP ENROL-PARK', 'Yes', 193);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (32, '', 'RQST FOR REVIEW WAS RECVD AFTER CITATION WAS ALREADY PD', 'PROTESTED PAID', 'Yes', 205);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (33, '', 'SEND CITIZEN TICKET: REQUEST COPY OF PARKING TICKET', 'REQ COPY OF PARK TKT', 'Yes', 209);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (34, '', 'DRIVE AWAY SEND TICKET TO CITIZEN', 'DRIVE AWAY', 'Yes', 210);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (35, '', 'REQ FOR MORE INFORMATION FROM THE CITIZEN', 'REQ FOR INFO PARKING', 'Yes', 211);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (36, '', 'CLAIM PAID CITATION PROVIDE PROOF OF PAYMENT (PARKING)', 'CLAIM PAID PROV PROF', 'Yes', 212);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (37, 'V', 'LETTER STATING CITATION HAS BEEN FOUND TO BE VALID', 'VALID TICKET IR', 'Yes', 213);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (38, '', 'DECLARATION OF INABILITY TO PAY WAIVER - PKG ADMIN REVIEW', 'INABILITY TO PAY', 'Yes', 214);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (39, '', 'PROMPT CITIZEN TO PROVIDE PAYMENT FOR PARKING VIOLATION', 'PROVIDE PAYMENT PARK', 'Yes', 216);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (40, '', 'PENDING REVIEW', 'PENDING REVIEW', 'Yes', 220);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (41, '', 'ABSTRACT LETTER FOR PARKING', 'PARKING ABSTRACT', 'Yes', 222);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (42, '', 'LTR EXPLAINING PARKING FINES ARE NOT EXEMPT FROM DISCHARGE', 'BANKRUPTCY', 'Yes', 224);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (43, '', 'PARKING FINES ARE NOT EXEMPT FROM DISCHARGE - NO APPEAL FORM', 'BANKRUPTCY NO APPEAL', 'Yes', 225);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (44, '', 'OFFICER CORRECTED TKT: THIS LETTER PROVIDES CITIZEN PROOF', 'PKG TKT CORRECTION', 'Yes', 228);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (45, '', 'REQUEST FOR REVIEW RECEIVED AFTER DEADLINE', 'TOO LATE', 'Yes', 245);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (46, '', 'LTR INDICATING PYMNT DUE BEFORE HEARING CAN BE SCHEDULED', 'REQ PYMT FOR HEAR', 'Yes', 254);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (47, '', 'PARKING HEARING INTERPRETER', 'PRK HEARING INTERPRE', 'Yes', 262);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (48, '', 'INSUFFICIENT DOCUMENTATION SUBMITTED FOR PAYMENT WAIVER', 'PYMT WAIVER DENIED P', 'Yes', 264);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (49, '', 'WAIVER APPROVED - HEARING REQUEST FORM INCLUDED', 'PYMT WAIVER ACCEPTED', 'Yes', 266);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (50, '', 'REQ INTER AND PAY WAVE', 'REQ INTER AND PAY WA', 'Yes', 267);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (51, '', 'REQ PAY WAIVER NO PROOF', 'REQ PAY WAIVER NO PR', 'Yes', 268);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (52, '', 'CTZN PROVIDED BLANK CHECK CTZN PROMT TO CORRECT AND RESEND', 'PKG BLANK CHECK', 'Yes', 275);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (53, '', 'PROMPT CTZN TO MAKE CHECK OUT TO MTA PARKING ADMIN', 'MAKE CHK OUT TO MTA', 'Yes', 276);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (54, '', 'RECIVED DAMAGED CHECK PROMPT CTZN TO RESEND', 'DAMAGED CHECK PRK', 'Yes', 277);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (55, '', 'DO NOT USE - LETTER WILL BE GENERATED BY HEARING EXAMINER', 'ADMIN HEARING DISMIS', 'No', 280);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (56, '', 'APPEAL AT SUPERIOR COURT - CITATION DISMISSED', 'SUPERIOR CRT DISMISS', 'Yes', 281);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (57, '', 'CITATION CLOSED DUE TO NO SHOW AT HEARING - PAYMENT DUE', 'FAILURE TO APPEAR', 'Yes', 282);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (58, 'V', 'DO NOT USE - LETTER WILL BE GENERATED BY HEARING EXAMINER', 'VALID TICK ADMIN HR', 'No', 283);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (59, 'V', 'APPEAL AT SUPERIOR COURT - CITATION IS VALID', 'VALID TICKET SC', 'Yes', 284);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (60, '', 'PARKING - SUPERIOR COURT APPEAL - AFFIRMED W/ PAYMENT PLAN', 'AFFIRMED IPP SC', 'Yes', 285);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (61, '', 'ADMINISTRATIVE REVIEWS SENT TO CLIENT FOR DECISION (P & T)', 'AR SENT TO CLIENT', 'Yes', 410);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (62, '', 'ADMIN REVIEWS RECIEVE BACK FROM CLIENT WITH A DECISION (P&T)', 'AR REC FROM CLIENT', 'Yes', 420);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (63, '', 'MARKER TO TRACK WHEN ALL HEARINGS ARE SCHEDUALED P&T', 'HEARING SCHEDULED', 'Yes', 430);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (64, '', 'SUPERIOR COURT PACKET IS CREATED, READY TO SEND TO COURT', 'SUP CRT PACKET MADE', 'Yes', 438);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (65, '', 'SUPERIOR COURT PACKET HAS BEEN SENT TO THE COURT', 'SUP CRT PACKET SENT', 'Yes', 439);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (66, '', 'SUPERIOR COURT DECISION RECIEVED', 'SUPCRTDECISIONRECIEV', 'Yes', 440);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (67, '', 'DISMISSED - DISABLED PERSON VIOLATION INITIAL REVIEW', 'DISMISSED DP VIOL', 'Yes', 501);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (68, '', '$25 FEE DUE DISABLED PERSON VIOLATION INITIAL REVIEW', '25 FEE DUE DP VIOL', 'Yes', 503);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (69, '', 'LTR $25 FEE IS DUE IN ORDER TO DISMISS HC VIOLATION', 'HANDCPD VIOLATION', 'Yes', 504);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (70, '', 'INCOMPLETE INFORMATION DISABLED PERSON VIOLATION INIT REVIEW', 'INCOMPLETE INFO DP', 'Yes', 505);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (71, '', 'GENERAL PHONE MARKER', 'PHONE MARKER', 'Yes', 600);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (72, '', 'RQST FOR REVIEW WAS RECVD AFTER CITATION WAS ALREADY PD', 'PROTESTED PAID', 'No', 605);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (73, '', 'REQUEST FOR REVIEW RECEIVED AFTER DEADLINE', 'TOO LATE FOR REVIEW', 'No', 606);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (74, '', 'ISSUING OFFICER MADE A CORRECTION AFTER CITATION WAS ISSUED', 'NOTICE OF CORRECTION', 'Yes', 613);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (75, 'V', 'LETTER STATING CITATION HAS BEEN FOUND TO BE VALID', 'VALID CITE AR', 'Yes', 622);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (76, 'D', 'LETTER STATING CITATION HAS BEEN DISMISSED', 'CITE DISMISSED AR', 'Yes', 650);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (77, 'D', 'LETTER STATING CITATION HAS BEEN DISMISSED', 'CITE DISMISSED AR OR', 'Yes', 651);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (78, '', 'WE RCVD CORR BUT IT WAS UNCLEAR AND/OR NO PYMT WAS MADE', 'NO PAYMENT', 'Yes', 657);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (79, '', 'LIABLE (TRANSIT)', 'LIABLE (T)', 'Yes', 801);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (80, '', 'NOT LIABLE (TRANSIT)', 'NOT LIABLE (T)', 'Yes', 802);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (81, '', 'FAILURE TO APPEAR (TRANSIT)', 'FAILURE TO APPEAR(T)', 'Yes', 803);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (82, '', 'TRANSIT CITATION IDENTIFIED INCORRECT PERSON IN VIOLATION', 'WRONG1 PERSON', 'Yes', 804);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (83, '', 'TRANSIT - REQ FOR REVIEW RECD AFTER VIOLATION PAID', 'PROTESTED WHEN PD', 'Yes', 805);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (84, '', 'THE HEARING OFFICER HAS AUTHORIZED A PAYMENT PLAN(TRANSIT)', 'IPP LIABLE (T)', 'Yes', 807);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (85, '', 'CTZN REQUEST COPY OF TRANSIT TICKET', 'REQ COPY OF TRAN TKT', 'Yes', 809);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (86, '', 'CTZN WALKED AWAY BEFORE TAKING TICKET', 'WALK AWAY', 'Yes', 810);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (87, '', 'REQ FOR MORE INFORMATION FROM THE CITIZEN', 'REQ FOR INFO TRANSIT', 'Yes', 811);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (88, '', 'CLAIM PAID CITATION PROVIDE PROOF OF PAYMENT (TRANSIT)', 'CLAIM PAY PROV PROOF', 'Yes', 812);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (89, '', 'TRANSIT - VALID TICKET', 'VALID TICKET', 'Yes', 813);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (90, '', 'DEC OF INABILITY TO PAY WAIVER - TRANSIT ADMIN REVIEW', 'INABILITY TO PAY', 'Yes', 814);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (91, '', 'TRANSIT - BOUNCED CHECK', 'BOUNCED CHECK', 'Yes', 815);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (92, '', 'PROMPT CITIZEN TO PROVIDE PAYMENT FOR TRANSIT VIOLATION', 'PROVIDE PAYMENT TRAN', 'Yes', 816);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (93, '', 'COMMUNITY SRVC HEARING LIABLE OFFICER COMMENTS (TRANSIT)', 'CS HRG LIABLE (T)', 'Yes', 819);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (94, '', 'TRANSIT - SUSPEND - PENDING REVIEW', 'SUSPEND PEND REVIEW', 'Yes', 820);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (95, '', 'TRANSIT - VALID EXCLUSION', 'VALID EXCLUSION', 'Yes', 823);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (96, '', 'TRANSIT - BANKRUPTCY', 'BANKRUPTCY', 'Yes', 824);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (97, '', 'TRANSIT - BANKRUPTCY - NO APPEAL FORM', 'BANKRUPTCY NO APPEAL', 'Yes', 825);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (98, '', 'INFORM CTZN OF VIOLATION CORRECTION TRANSIT', 'TRAN TKT CORRECTION', 'Yes', 828);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (99, '', 'TRANSIT REFUND', 'TRANSIT REFUND', 'Yes', 829);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (100, '', 'LIABLE COMMUNITY SERVICE GRANTED (TRANSIT)', 'LIABLE CMNTY SVC (T)', 'Yes', 830);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (101, '', 'COMMUNITY SERVICE (T) - DEFAULTED-NOT COMPLETED,NO EXTENSION', 'CMNTY SVC REF (T) DF', 'Yes', 833);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (102, '', 'TRANSIT RETURNED CHECK', 'TRS RETURNED CHECK', 'Yes', 835);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (103, '', 'TRANSIT - TOO LATE TO CONTEST - ADMIN HEARING', 'TOO LATE TO CONTEST', 'Yes', 845);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (104, '', 'TRANSIT - VIOLATION HAS BEEN DISMISSED', 'DISMISS TICKET', 'Yes', 850);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (105, '', 'TAP DISMISSED TICKET INITIAL REVIEW', 'TAP DISMISS INIT REV', 'Yes', '851');

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (106, '', 'TRANSIT - PAYMENT REQUIRED TO SCHEDULE HEARING', 'PAYMENT REQUIRED', 'Yes', 854);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (107, '', 'TRANSIT HEARING INTERPRETER REQUESTED', 'TRN HEARING INTRPRTR', 'Yes', 862);
 
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (108, '', 'TRANSIT - HEARING SCHEDULED - INCLUDES INSTRUCTIONS', 'SCHEDULED HEARING', 'Yes', 863);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (109, '', 'TRANSIT - PAYMENT WAIVER DENIED - INSUFFICIENT DOCUMENTATION', 'PMT WAIVER DENIED', 'Yes', 864);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (110, '', 'TRANSIT - PMT WAIVER APPROVED - HEARING REQ FORM INCLUDED', 'PMT WAIVER ACCEPTED', 'Yes', 866);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (111, '', 'REQ INTER AND PAY WAVE', 'REQ INTER AND PAY WA', 'Yes', 867);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (112, '', 'REQ PAY WAIVER NO PR', 'REQ PAY WAIVER NO PR', 'Yes', 868);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (113, '', 'CTZN PROVIDED BLANK CHECK CTZN PROMT TO CORRECT AND RESEND', 'TRN BLANK CHECK', 'Yes', 875);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (114, '', 'PROMT CTZN TO RESEND CHECK PAYABLE TO MTA TRANSIT COURT', 'MAKE PAY TO MTA TRAN', 'Yes', 876);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (115, '', 'DAMAGED CHECK PROMPT CTZN TO RESEND (TRANSIT)', 'DAMAGED CHECK TRN', 'Yes', 877);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (116, '', 'DO NOT USE - LETTER WILL BE GENERATED BY HEARING EXAMINER', 'TICKET DISMISSED TKT', 'Yes', 880);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (117, '', 'TRANSIT - SUPERIOR COURT APPEAL - TICKET DISMISSED', 'DISM TKT SUP COURT', 'Yes', 881);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (118, '', 'TRANSIT - FAILURE TO APPEAR - ADMIN HEARING - PAYMENT DUE', 'FAILURE TO APPEAR', 'Yes', 882);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (119, '', 'DO NOT USE - LETTER WILL BE GENERATED BY HEARING EXAMINER', 'VALID TICKET ADM HR', 'Yes', 883);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (120, '', 'TRANSIT - VALID TICKET - SUPERIOR COURT APPEAL', 'VALID TICKET SUP CT', 'Yes', 884);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (121, '', 'TRANSIT - SUPERIOR COURT - AFFIRMED W/ PAYMENT PLAN', 'TRN AFFIRMED IPP SC', 'Yes', 885);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (122, '', 'INSTALLMENT PAYMENT PLAN - ENROLLMENT CONFIRMATION - TRANSIT', 'IPP ENROL CONF-TRANS', 'Yes', 890);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (123, '', 'INSTALLMENT PAYMENT PLAN - NO FIRST PAYMENT - TRANSIT', 'IPP NO FIRST PAYM PK', 'Yes', 891);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (124, '', 'INSTALLMENT PAYMENT PLAN - NOTICE OF DEFAULT - TRANSIT', 'IPP-DEFAULT-TRAN', 'Yes', 892);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (125, '', 'INSTALLMENT PAYMENT PLAN - ENROLLMENT - TRANSIT', 'IPP ENROL-TRANSIT', 'Yes', 893);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (126, '', 'EXCLUSION HEARING LIABLE', 'EXCLUSION HRG LIABLE', 'Yes', 895);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (127, '', 'EXCLUSION HEARING FAILURE TO APPEAR', 'EXCLUSION HRG FTA', 'Yes', 896);
INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (128, '', 'TRANSIT - REQ FOR REVIEW RECD AFTER VIOLATION PAID', 'PROTESTED WHEN PD', 'No', 905);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (129, '', 'TRANSIT - REQUEST FOR REVIEW RECD AFTER DEADLINE', 'TOO LATE REVIEW', 'Yes', 906);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (130, '', 'TRANSIT - ISSUING OFCR MADE CORR AFTER VIOLATION ISSUED', 'NOTICE OF CORRECTION', 'Yes', 913);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (131, '', 'AUTOMATED LETTER WHEN PERSON ADDED TO PERSONAL SERVICE RPRT.', 'NOTICE OF EXCLUSION', 'No', 915);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (132, '', 'NIXIE NOE WHICH IS INDEXED TO ETIMS BUT NOT MAILED', 'NIXIE NOTICE OF EXCL', 'Yes', 935);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (133, '', 'TRANSIT - RECD CORRESONDENCE BUT UNCLEAR AND/OR NO PMT MADE', 'NO PAYMENT', 'Yes', 957);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (134, '', 'TRANSIT SCHOOL REDUCTION REVERSED', 'TRANST SCHOOL UNPAID', 'Yes', 981);

INSERT INTO `ecitation`.`CORRESP_CODE` (`id`, `CLS`, `CORRESP_DESC`, `FULL_NAME`, `IS_ACTIVE`, `TYP_CD`) VALUES (135, '', 'TRANSIT - TRANSIT SCHOOL CERT RECD, NO PAYMENT RECD', 'TRANSIT SCHOOL', 'Yes', 990);

