INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('1', 'CASHIER-ONLINE', '1');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('2', 'LOCKBOX', '2');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('3', 'DMV', '3');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('4', 'KIOSK', '4');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('5', 'FTB INTERCEPT', '5');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('6', 'LA CNTY METRO', '6');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('7', 'PAY-BY-PHONE', '7');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('8', 'PRODUCTION CNTL', '8');
INSERT INTO `ecitation`.`PAYMENT_SOURCE` (`id`, `FULL_NAME`, `TYP_CD`) VALUES ('9', 'PAY-BY-WEB', '9');