insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (1,6001,'RAIL-BLUE LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (2,6002,'5TH ST','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (3,6003,'1ST ST','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (4,6004,'DOWNTOWN LONG BEACH','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (5,6005,'PACIFIC AV','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (6,6006,'ANAHEIM ST','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (7,6007,'PACIFIC COAST HWY','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (8,6008,'WILLOW ST','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (9,6009,'WARDLOW','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (10,6011,'DEL AMO','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (11,6012,'ARTESIA','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (12,6013,'COMPTON','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (13,6014,'WILLOWBROOK/ROSA PARKS','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (14,6015,'103rd STATION/WATTS TOWERS','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (15,6016,'FIRESTONE','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (16,6017,'FLORENCE','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (17,6018,'SLAUSON','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (18,6019,'VERNON','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (19,6020,'WASHINGTON','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (20,6021,'SAN PEDRO ST','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (21,6022,'GRAND/LATTC','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (22,6023,'PICO','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (23,6024,'7TH ST/METRO CENTER','BLUE','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (24,6051,'RAIL-GREEN LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (25,6052,'REDONDO BEACH','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (26,6053,'DOUGLAS','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (27,6054,'EL SEGUNDO','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (28,6055,'MARIPOSA','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (29,6056,'AVIATION/LAX','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (30,6059,'HAWTHORNE/LENNOX','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (31,6060,'CRENSHAW','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (32,6061,'VERMONT/ATHENS','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (33,6062,'HARBOR FWY','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (34,6063,'AVALON','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (35,6064,'WILLOWBROOK/ROSA PARKS','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (36,6065,'LONG BEACH BL','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (37,6067,'LAKEWOOD BL','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (38,6068,'NORWALK','GREEN','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (39,6401,'UNION STATION','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (40,6402,'CIVIC CENTER/GRAND PARK','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (41,6403,'PERSHING SQUARE','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (42,6404,'7TH ST/METRO CENTER','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (43,6405,'RAIL-RED LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (44,6406,'WESTLAKE/MACARTHUR PARK','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (45,6407,'WILSHIRE/VERMONT','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (46,6408,'WILSHIRE/NORMANDIE','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (47,6409,'VERMONT/BEVERLY','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (48,6410,'WILSHIRE/WESTERN','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (49,6411,'VERMONT/SANTA MONICA','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (50,6413,'VERMONT/SUNSET','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (51,6415,'HOLLYWOOD/WESTERN','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (52,6417,'HOLLYWOOD/VINE','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (53,6419,'HOLLYWOOD/HIGHLAND','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (54,6421,'UNIVERSAL CITY/STUDIO CITY','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (55,6423,'NORTH HOLLYWOOD','RED','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (56,6501,'UNION STATION','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (57,6502,'LITTLE TOKYO/ARTS DISTRICT','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (58,6503,'RAIL-GOLD LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (59,6504,'PICO/ALISO','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (60,6505,'CHINATOWN','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (61,6506,'MARIACHI PLAZA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (62,6507,'LINCOLN/CYPRESS PARK','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (63,6508,'SOTO','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (64,6509,'HERITAGE SQUARE','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (65,6510,'EAST PORTAL','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (66,6511,'SOUTHWEST MUSEUM','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (67,6512,'INDIANA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (68,6513,'HIGHLAND PARK','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (69,6514,'MARAVILLA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (70,6515,'SOUTH PASADENA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (71,6516,'EAST LA CIVIC CENTER','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (72,6517,'FILLMORE','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (73,6518,'ATLANTIC','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (74,6519,'DEL MAR','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (75,6521,'MEMORIAL PARK','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (76,6523,'LAKE','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (77,6525,'ALLEN','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (78,6527,'SIERRA MADRE VILLA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (79,6529,'ARCADIA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (80,6531,'MONROVIA','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (81,6533,'DUARTE/CITY OF HOPE','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (82,6535,'IRWINDALE','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (83,6537,'AZUSA DOWNTOWN','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (84,6539,'APU/CITRUS','GOLD','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (85,6559,'RAIL-GOLD LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (86,6601,'7TH ST/METRO CENTER','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (87,6603,'PICO','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (88,6605,'LATTC/ORTHO INSTITUTE','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (89,6607,'JEFFERSON/USC','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (90,6609,'EXPO PARK/USC','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (91,6611,'EXPO/VERMONT','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (92,6613,'EXPO/WESTERN','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (93,6615,'EXPO/CRENSHASW','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (94,6617,'FARMDALE','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (95,6619,'EXPO/LA BREA','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (96,6621,'LA CIENEGA/JEFFERSON','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (97,6623,'CULVER CITY','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (98,6625,'PALMS','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (99,6627,'WESTWOOD/RANCHO PARK','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (100,6629,'EXPO/SEPULVEDA','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (101,6631,'EXPO/BUNDY','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (102,6633,'26TH ST/BERGAMONT','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (103,6635,'17TH ST/SMC','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (104,6637,'DOWNTOWN SANTA MONICA','EXPO','RAIL');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (105,6639,'RAIL-EXPO LINE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (106,6701,'WARNER CENTER','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (107,6702,'CANOGA','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (108,6704,'DE SOTO','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (109,6705,'PIERCE COLLEGE','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (110,6706,'SHERMAN WAY','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (111,6707,'TAMPA','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (112,6708,'RESEDA','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (113,6709,'ROSCOE','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (114,6710,'BALBOA','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (115,6711,'NORDHOFF','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (116,6712,'WOODLEY','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (117,6713,'SEPULVEDA','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (118,6714,'CHATSWORTH','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (119,6715,'VAN NUYS','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (120,6717,'WOODMAN','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (121,6719,'VALLEY COLLEGE','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (122,6721,'LAUREL CANYON','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (123,6723,'NORTH HOLLYWOOD','ORANGE','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (124,6811,'PASADENA','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (125,6812,'MONROVIA','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (126,6813,'EL MONTE/ROSEMEAD/HACIENDA HEIGHTS','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (127,6814,'ALHAMBRA','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (128,6815,'EL MONTE TERMINAL','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (129,6815,'EL MONTE','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (130,6816,'EL MONTE','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (131,6817,'CAL STATE LA','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (132,6818,'LAC+USC MEDICAL CTR','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (133,6821,'COVINA/INDUSTRY','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (134,6822,'POMONA/CLAREMONT','PATROL1','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (135,6831,'NORWALK','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (136,6832,'LAKEWOOD/ARTESIA','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (137,6833,'LONG BEACH/SIGNAL HILL','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (138,6834,'SOUTH GATE','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (139,6835,'MAYWOOD/BELL','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (140,6836,'WALNUT PARK','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (141,6837,'ELA/COMMERCE','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (142,6841,'WHITTIER','PATROL2','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (143,6851,'COMPTON/CARSON','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (144,6852,'SOUTH LA CORRIDOR/WATTS','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (145,6853,'WILMINGTON/SAN PEDRO','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (146,6854,'MANCHESTER','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (147,6855,'HARBOR FWY','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (148,6856,'ROSECRANS','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (149,6857,'HARBOR GATEWAY TRANSIT CENTER','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (150,6861,'BEACH CITIES','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (151,6862,'ARTESIA TRANSIT CENTER','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (152,6862,'HARBOR/GATEWAY','DIV','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (153,6863,'CARSON','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (154,6864,'PACIFIC COAST HIGHWAY','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (155,6865,'HARBOR/BEACON PARK AND RIDE','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (156,6871,'INGLEWOOD/HAWTHORNE','PATROL3','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (157,6872,'CULVER CITY/BALDWIN HILLS','PATROL4','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (158,6873,'SANTA MONICA','PATROL4','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (159,6874,'BEVERLY HILLS/WEST HOLLYWOOD','PATROL4','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (160,6875,'SAN FERNANDO','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (161,6876,'BURBANK','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (162,6877,'GLENDALE','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (163,6878,'WESTWOOD/PACIFIC PALISADES','PATROL4','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (164,6881,'MALIBU','PATROL4','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (165,6882,'AGOURA HILLS/CALABASAS','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (166,6883,'SANTA CLARITA','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (167,6884,'WEST HILLS/NORTH HOLLYWOOD / ENCINO','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (168,6885,'CHATSWORTH/SUNLAND/NORTHRIDGE','PATROL5','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (169,6891,'LOS ANGELES DOWNTOWN','PATROL6','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (170,6892,'LINCOLN HEIGHTS/EAGLE ROCK','PATROL6','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (171,6893,'HYDE PARK/CRENSHAW','PATROL6','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (172,6894,'HOLLYWOOD HILLS/WILSHIRE','PATROL6','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (173,6895,'37TH ST/USC','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (174,6896,'SLAUSON','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (175,6897,'DOWNTOWN LA (STREET BUS STOPS)','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (176,6898,'UNION STATION','SILVER','BUS');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (177,6901,'USG/COMPLEX (WEST SIDE)','USG','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (178,6902,'USG/COMPLEX (EAST SIDE)','USG','BLDG');
insert into REPORTINGDISTRICTS(id,`rdNumber`,`stationName`,`line`,`vehicle`) values (179,6941,'FULLERTON/ANAHEIM','PATROL2','BUS');