insert into STATES(id,`name`,`description`) values (1,'Al','Alabama');
insert into STATES(id,`name`,`description`) values (2,'AK','Alaska');
insert into STATES(id,`name`,`description`) values (3,'AZ','Arizona');
insert into STATES(id,`name`,`description`) values (4,'AR','Arkansas');
insert into STATES(id,`name`,`description`) values (5,'CA','California');
insert into STATES(id,`name`,`description`) values (6,'CO','Colorado');
insert into STATES(id,`name`,`description`) values (7,'CT','Connecticut');
insert into STATES(id,`name`,`description`) values (8,'DE',' Delaware');
insert into STATES(id,`name`,`description`) values (9,'FL','Florida');
insert into STATES(id,`name`,`description`) values (10,'GA','Georgia');
insert into STATES(id,`name`,`description`) values (11,'HI','Hawaii');
insert into STATES(id,`name`,`description`) values (12,'ID','Idaho');
insert into STATES(id,`name`,`description`) values (13,'IL','Illinois');
insert into STATES(id,`name`,`description`) values (14,'IN','Indiana');
insert into STATES(id,`name`,`description`) values (15,'IA','Iowa');
insert into STATES(id,`name`,`description`) values (16,'KS','Kansas');
insert into STATES(id,`name`,`description`) values (17,'KY','Kentucky[D]');
insert into STATES(id,`name`,`description`) values (18,'LA','Louisiana');
insert into STATES(id,`name`,`description`) values (19,'ME','Maine');
insert into STATES(id,`name`,`description`) values (20,'MD','Maryland');
insert into STATES(id,`name`,`description`) values (21,'MA',' Massachusetts[E]');
insert into STATES(id,`name`,`description`) values (22,'MI',' Michigan');
insert into STATES(id,`name`,`description`) values (23,'MN',' Minnesota');
insert into STATES(id,`name`,`description`) values (24,'MS',' Mississippi');
insert into STATES(id,`name`,`description`) values (25,'MO','Missouri'); 	
insert into STATES(id,`name`,`description`) values (26,'MT',' Montana');
insert into STATES(id,`name`,`description`) values (27,'NE','Nebraska');	
insert into STATES(id,`name`,`description`) values (28,'NV','Nevada'); 	
insert into STATES(id,`name`,`description`) values (29,'NH','New Hampshire');	
insert into STATES(id,`name`,`description`) values (30,'NJ','New Jersey'); 
insert into STATES(id,`name`,`description`) values (31,'NM','New Mexico');
insert into STATES(id,`name`,`description`) values (32,'NY','New York'); 	
insert into STATES(id,`name`,`description`) values (33,'NC','North Carolina');
insert into STATES(id,`name`,`description`) values (34,'ND','North Dakota');
insert into STATES(id,`name`,`description`) values (35,'OH','Ohio');
insert into STATES(id,`name`,`description`) values (36,'OK','Oklahoma');
insert into STATES(id,`name`,`description`) values (37,'OR','Oregon');
insert into STATES(id,`name`,`description`) values (38,'PA','Pennsylvania'); 
insert into STATES(id,`name`,`description`) values (39,'RI','Rhode Island');
insert into STATES(id,`name`,`description`) values (40,'SC','South Carolina');
insert into STATES(id,`name`,`description`) values (41,'SD','South Dakota');
insert into STATES(id,`name`,`description`) values (42,'TN','Tennessee');
insert into STATES(id,`name`,`description`) values (43,'TX','Texas');
insert into STATES(id,`name`,`description`) values (44,'UT','Utah');
insert into STATES(id,`name`,`description`) values (45,'VT','Vermont');
insert into STATES(id,`name`,`description`) values (46,'VA','Virginia');
insert into STATES(id,`name`,`description`) values (47,'WA','Washington');
insert into STATES(id,`name`,`description`) values (48,'WV','West Virginia');
insert into STATES(id,`name`,`description`) values (49,'WI','Wisconsin');
insert into STATES(id,`name`,`description`) values (50,'WY','Wyoming');