INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (1, '023', '25', 'CLAIM OF NON-OWNERSHIP OF VEHICLE', 'DECOFNON PART 1', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (2, '030', '25', 'LETTER TO NEW OWNER (AS REPORTED BY REGISTERED OWNER)', 'DEC OF NON NEW', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (3, '050', '21', 'MANAGER USE ONLY - FOR ISSUES THAT NEED MORE TIME TO RESOLVE', 'MANAGER REVIEW', 'Yes', 'B');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (4, '063', '90', 'HEARING HAS BEEN SCHEDULED - INCLUDES INSTRUCTIONS', 'HEARING SCHED', 'Yes', '5');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (5, '089', '1', '', 'CANCEL SUSPEND', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (6, '097', '0', 'IDENTIFIED AS A WARNING VIOLATION OR TICKET', 'WARNING', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (7, '098', '0', 'TICKET VOIDED BY OFFICER', 'VOID', 'Yes', 'P');
INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (8, '099', '15', 'SCHEDULED HEARING', 'SCHED HEAR', 'Yes', 'T');
INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (9, '106', '25', 'REQ FOR INITIAL REVIEW ON PKG CITE HAD PASSED TIME PERIOD', 'TOO LATE REVIEW', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (10, '116', '120', 'RECEIVED DMV PAYMENT RECEIPT FROM PATRON', 'DMV PRF OF PAYMENT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (11, '119', '120', 'COMMUNITY SRVC(P)-HEARING LIABLE OFFICER COMMENTS', 'CS HRG LIABLE (P)', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (12, '130', '120', 'COMMUNITY SERVICE REFERRED (P) - LIABLE', 'CMNTY SVC REF (P) LI', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (13, '131', '999', 'COMMUNITY SERVICE (P) - COMPLETED SUBMITTED CERTIFICATE', 'CMNTY SVC REF (P) CC', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (14, '132', '90', 'COMMUNITY SERVICE (P) - EXTENSION GRANTED', 'CMNTY SVC REF (P) EG', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (15, '133', '1', 'COMMUNITY SERVICE (P) - DEFAULTED-NOT COMPLETED,NO EXTENSION', 'CMNTY SVC REF (P) DF', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (16, '134', '30', 'COMMUNITY SRVC(P)-DISQUALIFY- RUDE/UNCOOPERATIVE/DISRUPTIVE', 'CMNTY SVC REF (P) DQ', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (17, '150', '0', 'LETTER STATING CITATION HAS BEEN DISMISSED - INITIAL REVIEW', 'REVIEW - DISMISSED', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (18, '151', '0', 'MONTHLY PARKING PERMIT WAS VALID ON THE DATE OF ISSUANCE', 'VALIDPERMITDISM', 'No', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (19, '182', '25', 'NO FRONT LICENSE PLATE - PROOF OF CORRECTION', 'NO FRONT PLATE', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (20, '183', '1', 'PROOF OF CORRECTION-DISMISSED TABS & NO FRONT PLATE-PARKING', 'REC PROOF AND PAY', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (21, '184', '25', 'EXPIRED REGISTRATION TABS - PROOF OF CORRECTION', 'EXPIRED TABS', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (22, '185', '15', 'PENALTIES - NO FRONT PLATES & TABS', 'PENAL NO FR PLT TAB', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (23, '186', '20', 'REC PROOF NOT PAY', 'REC PROOF NOT PAY', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (24, '187', '25', 'INFORMATION ON 4000A1 VIOLATION PROCESS', '4000A1 INFORMATION', 'No', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (25, '204', '999', 'CITATION DISMISSED', 'INTERNAL ERROR', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (26, '209', '1', 'CITIXEN REQUESTS FOR COPY OF PARKING TICKET', 'REQ COPY OF PK TKT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (27, '212', '30', 'CLAIM PAID CITATION REQ PROOF OF PAYMENT (PARKING)', 'CLAIM PAY PROV PROOF', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (28, '213', '25', 'LETTER STATING CITE FOUND TO BE VALID - INITIAL REVIEW', 'REVIEW - VALID', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (29, '214', '21', 'DECLARATION OF INABILITY TO PAY - PKG ADMIN REVIEW', 'INABILITY TO PAY P', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (30, '216', '21', 'PROMPT CITIZEN FOR PAYMENT OF PARKING VIOLATION', 'PROVIDE PAYMENT PARK', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (31, '220', '30', 'CORRESPONDENCE FOR INITIAL REVIEW', 'PENDING REVIEW', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (32, '224', '25', 'PARKING FINES NOT EXEMPT FROM DISCHARGE - BANKRUPTCY', 'FINES NOT EXEMPT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (33, '230', '25', 'CLAIM OF NON-OWNERSHIP OF VEHICLE', 'DECOFNON PART 1', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (34, '242', '999', 'TICKET IS ENROLLED IN IPP', 'IPP ENRLMT', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (35, '243', '1', 'IPP HAS BEEN CANCELLED', 'IPP CANCEL', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (36, '245', '25', 'REQ FOR ADMIN HEARING FOR PKG CITE PASSED TIME SPECIFIED', 'TOO LATE PKG AH', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (37, '254', '25', 'PAYMENT DUE BEFURE HEARING CAN BE SCHEDULED', 'PMT DUE FOR HEARING', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (38, '262', '90', 'PARKING HEARING - INTERPRETER REQUESTED', 'PRK HEARING INTERPRE', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (39, '264', '90', 'PAYMENT WAIVER - INSUFFICIENT DOCUMENTATION SUBMITTED', 'PMT WAIVER INSUF DOC', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (40, '266', '90', 'PAYMENT WAIVER APPROVED - HEARING REQUEST FORM INCLUDED', 'PMT WAIV APPROVED', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (41, '267', '90', 'REQ INTER AND PAY WAVE', 'REQ INTER AND PAY WA', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (42, '268', '90', 'REQ PAY WAIVER NO PROOF', 'REQ PAY WAIVER NO PR', 'Yes', 'T');
INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (43, '276', '30', 'PROMPT CTZN TO RESEND CHK,RECEIVED CHK NOT PAYABLE TO MTA', 'NOT PAYABLE TO MTA', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (44, '277', '30', 'PROMPT CTZN TO RESEND CHECK,RECIEVED DAMAGED CHECK PARKING', 'DAMAGED CHECK PARKIN', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (45, '280', '0', 'HEARING DECISION LETTER - CITATION DISMISSED', 'HEARING - DISMISSED', 'No', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (46, '281', '0', 'SUPERIOR COURT APPEAL - CITATION DISMISSED', 'SC PARKING REVERSED', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (47, '282', '25', 'FAILURE TO APPEAR - CITATION CLOSED, PAYMENT DUE', 'FAIL TO APPEAR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (48, '283', '40', 'HEARING DECISION LETTER - CITATION VALID', 'HEARING - VALID', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (49, '284', '25', 'SUPERIOR COURT - CITATION VALID', 'APPEAL - VALID', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (50, '285', '90', 'PARKING - SUPERIOR COURT - CITATION AFFIRMED W/ IPP', 'APPEAL - VALID IPP', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (51, '500', '21', 'MANAGER USE ONLY - FOR ISSUES THAT NEED MORE TIME TO RESOLVE', 'MANAGER REVIEW', 'Yes', 'B');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (52, '501', '0', 'DISMISSED - DISABLED PERSON VIOLATION', 'DP REVIEW DISMISSED', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (53, '503', '21', '$25 FEE DUE DISABLED PERSON VIOLATION INITIAL REVIEW', '25 FEE DUE DP', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (54, '504', '25', 'HANDICAPPED VIOLATION - $25 DUE TO DISMISS', '$25 DUE TO DISMISS', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (55, '505', '21', 'INCOMPLETE INFORMATION DISABLED PERSON VIOLATION INIT REVIEW', 'INCOMPLETE INFO', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (56, '630', '90', 'HEARING HAS BEEN SCHEDULED - INCLUDES INSTRUCTIONS', 'HEARING SCHED', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (57, '804', '25', 'WRONG PERSON IDENTIFIED AS RESPONSIBLE FOR TRANSIT VIOLATION', 'WRONG PERSON', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (58, '809', '1', 'CITIZEN REQUESTS FOR COPY OF TRANSIT TICKET', 'REQ COPY OF TRAN TKT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (59, '812', '30', 'CLIAM PAID CITATION REQ PROOF OF PAYMENT (TRANSIT)', 'CLAIM PAY PROV PROOF', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (60, '813', '25', 'TRANSIT - VIOLATION FOUND VALID ON INITIAL REVIEW', 'REVIEW VALID TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (61, '814', '21', 'DECLARATION OF INABILITY TO PAY WAIVER - TRNSIT ADMIN REVIEW', 'INABILITY TO PAY W T', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (62, '819', '120', 'COMMUNITY SRVC(T)-HEARING LIABLE OFFICER COMMENTS', 'CS HRG LIABLE (T)', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (63, '820', '30', 'TRANSIT - CORRESPONDENCE FOR INITIAL REVIEW', 'PEND REVIEW TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (64, '823', '30', 'TRANSIT - EXCLUSION FOUND VALID ON INITIAL REVIEW', 'EXCLUSION VALID TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (65, '824', '25', 'TRANSIT - FINES NOT EXEMPT FORM DISCHARGE FROM BANKRUPTCY', 'FINES NT EXEMPT TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (66, '830', '120', 'COMMUNITY SERVICE REFERRED (T) - LIABLE', 'CMNTY SVC REF (T) LI', 'Yes', 'T');
INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (67, '831', '999', 'COMMUNITY SERVICE (T) - COMPLETED SUBMITTED CERTIFICATE', 'CMNTY SVC REF (T) CC', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (68, '832', '90', 'COMMUNITY SERVICE (T) - EXTENSION GRANTED', 'CMNTY SVC REF (T) EG', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (69, '833', '1', 'COMMUNITY SERVICE (T) - DEFAULTED-NOT COMPLETED,NO EXTENSION', 'CMNTY SVC REF (T) DF', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (70, '834', '30', 'COMMUNITY SRVC(T)-DISQUALIFY- RUDE/UNCOOPERATIVE/DISRUPTIVE', 'CMNTY SVC REF (T) DQ', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (71, '845', '25', 'REQ FOR ADMIN HEARING FOR TRANS CITE PASSED TIME SPECIFIED', 'TOO LATE TO CONTEST', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (72, '850', '0', 'TRANSIT - VIOLATION DISMISSED ON INITIAL REVIEW', 'REVIEW DSMD TR', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (73, '851', '0', 'TAP DISMISSED TICKET INITIAL REVIEW', 'TAP DISMISSED', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (74, '854', '25', 'TRANSIT - PAYMENT DUE BEFORE HEARING SCHEDULED', 'PAY DUE HEARING TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (75, '862', '90', 'TRANSIT HEARING - INTERPRETER REQUESTED', 'TRN HEARING INTERPRT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (76, '863', '90', 'TRANSIT - HEARING SCHEDULED - WITH INSTRUCTIONS', 'HEAR SCHED TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (77, '864', '90', 'TRANSIT - PMT WAIVER - INSUFFICIENT DOCUMENTATION SUBMITTED', 'PAY WAIV INSUF TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (78, '866', '90', 'TRANSIT - PMT WAIVER APPROVED - HEARING REQ FORM INCLUDED', 'PAY WAIV APPR TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (79, '867', '90', 'REQ INTER AND PAY WAVE', 'REQ INTER AND PAY WA', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (80, '868', '90', 'REQ PAY WAIVER NO PROOF', 'REQ PAY WAIVER NO PR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (81, '877', '30', 'PROMPT CTZN TO RESEND CHECK,RECIEVED DAMAGED CHECK TRANSIT', 'DAMAGED CHECK TRNST', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (82, '881', '0', 'TRANSIT - SUPERIOR COURT APPEAL - CITATION REVERSED', 'APPEAL REVERSED SC', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (83, '882', '25', 'TRANSIT - FAILURE TO APPEAR - CITATION VALID', 'FAIL TO APP TR', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (84, '884', '25', 'TRANSIT - SUPERIOR COURT - CITATION AFFIRMED', 'APPEAL AFFIRMED', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (85, '885', '90', 'TRANSIT - SUPERIOR COURT APPEAL - CITATION AFFIRMED W/ IPP', 'APPEAL PAYMENT PLAN', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (86, '888', '21', '', 'TRANSIT SCHOOL', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (87, '901', '999', '', 'PRE-CONVERSION SUSP', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (88, '906', '25', 'REQ FOR INITIAL REVIEW ON TRANS CITE HAD PASSED TIME PERIOD', 'TOO LATE REVIEW', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (89, '910', '0', 'PERSONAL SERVICE TICKET ERRORS', 'PSTK ERRORS', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (90, '911', '999', '', 'PSTK LIABLE PROCESS', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (91, '912', '999', '', 'PSTK NOT LIABLE PRCS', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (92, '913', '25', 'NOTICE OF CORRECTION', 'NOTICE OF CORRECTION', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (93, '915', '999', '', 'NO IMAGE', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (94, '916', '1', '', 'IMAGE FOUND', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (95, '950', '0', 'FARE MEDIA REMEDY - TRANSIT TICKETS', 'FARE MEDIA REMEDY', 'Yes', 'P');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (96, '957', '25', 'SUSPEND WHILE REQUESTING PAYMENT', 'NO PAYMENT', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (97, '960', '999', '', 'DMV LOST CHECK', 'Yes', 'I');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (98, '980', '7', 'ALLOW 7 DAYS FOR PAYMENT', 'TRANSIT SCHOOL PAY', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (99, '989', '0', 'CANCEL CORREPONDENCE', 'CORRESPONDENCE CANCL', 'Yes', 'T');

INSERT INTO `ecitation`.`SUSPENDED_CODES` (`id`, `CODE`, `DAYS`, `DESCRIPTION`, `FULL_NM`, `IS_ACTIVE`, `TYPE`) VALUES (100, '990', '25', 'TRANSIT SCHOOL', 'TRANSIT SCHOOL', 'Yes', 'T');

